[[Uno]]
arch = "aarch64"
git-tree-sha1 = "8b0c32ab0d166fc3b547726d5618804f602a87fd"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "62065e2441cb3747ac77028d1d8fb7d581c7687d9b2573736f8d73e143490d4e"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a85825e4f5ff168fc1030396655de14fac09c8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "82ce708195f45178ed2e88fe3c7b97ec7ba4d19d4eb150a801c227d47d2bcaeb"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23d3f1b97f8e0b7c36c849fd9b20a6475b34027e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "71a23a8f8afaf33b6f9ac268889a2bd09b647f93c259f881da32ba4c3ec3839a"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41396303923edaefef5b3f26bff19004cb2d3b15"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "b03c7fb023713a29f5d8cd1fc67ae9fe84a2522b40fc87ee1d2695dd69198a32"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9d6138d1607d62a78eef881629c8d5b72083223"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "85650acc628ff9808cd3d3acaeef0c28e90139c9ed006d5b74dd6f248a4887fd"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "790bbcd179b0d454d676d897172cea9fe0799794"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "b1e34ff0b1d0b17f5e8f5aad3d788f745d41f59a4e70f6c1faff1ecf3937e8f7"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73df93e602aba9f199544e15576a4d778fa291e8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "d7648a41850c340a51b40d9776f6b525f02fdb649f664225b88426cbe53552ca"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f30bbb8e62b0bd31c002be7f91798660f4b2d32"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "5790439419f9e48f07b2f4cee4a24b2b679247b1cd1300e892f264da9c5bfe9e"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7455383f66b2606f8f2a456577b9d426cc747620"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "f5c018619f8bdf0298ef28529361a41d7bd3f36562bc95617457e2bb62295ba8"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7157252250b17973b7322af3893533040f59310"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "a76d3759a973811a37f7712f489e6f1e9814d881db26da33d89ac4e6cc1b7ff6"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ea5af2eeafb666609f125ad35413af8825bf26f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "c4a4da908cf8475f438cdea5e5c3e6f8f1f3b457101e390316187d26399405d4"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "88e6d4c627fb8afc52ee38b13d482ed746f79851"
libgfortran_version = "5.0.0"
os = "macos"

    [[Uno.download]]
    sha256 = "84e61e5006b1673ead2d0256d671368451648d4d0336f2ee14c6fe1416f536ef"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14bf89827e95e4f7f4c613c31da23f388a220d2c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "6debbb5bf1a4d20ff5af8d72df1027109575cca0f1b5e0c6713d19955d3663c9"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d36f3a12ee5324de35b8944c09cbb374c1190aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Uno.download]]
    sha256 = "35780d9dcad50da718c2ab868d1f8df604bc5add8d52b5c3e15f27162fe8624e"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Uno]]
arch = "x86_64"
git-tree-sha1 = "2b1d3350ea13afc6573b1d5fe785f28eedab4746"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Uno.download]]
    sha256 = "918ac91b0ca56b329a153ea80210f72e5d7fe2a7048b8cbce0331ab79ea9f8b9"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Uno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf21e43b614437128335c2035b8796a63e235d8f"
libgfortran_version = "5.0.0"
os = "windows"

    [[Uno.download]]
    sha256 = "376deee604ad3e1b4bd8f80d4f97d357f982f7269d37ce6372a0f7ae94671ee3"
    url = "https://github.com/JuliaBinaryWrappers/Uno_jll.jl/releases/download/Uno-v2.3.1+0/Uno.v2.3.1.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
